apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mantle.fullname" . }}-config
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
data:
  config.toml: |
{{ include "mantle.configToml" . | indent 4 }}
