{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mantle.fullname" . }}-api
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  selector:
    matchLabels:
      {{- include "mantle.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mantle.fullname" . }}-worker
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "mantle.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mantle.fullname" . }}-analytics-worker
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics-worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.analyticsWorker.minAvailable }}
  selector:
    matchLabels:
      {{- include "mantle.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: analytics-worker
{{- end }}
