apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mantle.fullname" . }}-secret
  labels:
    {{- include "mantle.labels" . | nindent 4 }}
type: Opaque
stringData:
  MANTLE_ADMIN_TOKEN: {{ required "secret.adminToken is required" .Values.secret.adminToken | quote }}
  POSTGRES_USER: {{ .Values.secret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secret.postgresDatabase | quote }}
