#!/usr/bin/env bash
# Bootstrap a fresh Ubuntu 22.04/24.04 EC2 instance for Mantle Docker Compose deploy.
# Usage: ./scripts/deploy-ec2-bootstrap.sh [clone-url]
set -euo pipefail

MANTLE_REPO_URL="${1:-https://github.com/YOUR_ORG/mantle.git}"
INSTALL_DIR="${MANTLE_INSTALL_DIR:-$HOME/mantle}"

echo "== Mantle EC2 bootstrap =="
echo "Repo: ${MANTLE_REPO_URL}"
echo "Install dir: ${INSTALL_DIR}"

if ! command -v git >/dev/null 2>&1; then
  echo "Installing git..."
  sudo apt-get update
  sudo apt-get install -y git ca-certificates curl ufw
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Installing Docker..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "${USER}" || true
  echo "Docker installed. You may need to log out and back in (or run: newgrp docker)."
fi

if [[ ! -d "${INSTALL_DIR}/.git" ]]; then
  echo "Cloning Mantle..."
  git clone "${MANTLE_REPO_URL}" "${INSTALL_DIR}"
else
  echo "Directory ${INSTALL_DIR} already exists — skipping clone."
fi

cd "${INSTALL_DIR}"

if [[ ! -f .env ]]; then
  echo "Creating .env from .env.example"
  cp .env.example .env
  if command -v openssl >/dev/null 2>&1; then
  {
    echo ""
    echo "# Generated by deploy-ec2-bootstrap.sh"
    echo "MANTLE_ADMIN_TOKEN=$(openssl rand -hex 32)"
  } >> .env
  fi
  echo "Review ${INSTALL_DIR}/.env before production use."
fi

cat <<EOF

Bootstrap complete.

Next steps:
  cd ${INSTALL_DIR}
  # Edit config.toml and .env as needed
  docker compose up -d --build
  curl -s http://localhost:8080/health
  ./scripts/smoke.sh

Full guide: docs/deploy-ec2.md
EOF
